### ISSUE TITLE
"fetch failed" when building on Vercel

### ISSUE THREAD

**Issue by faridghar** [medusajs/medusa-starter-default#101]
I'm trying to run the Medusa frontend on Vercel. During the `next build` command, I'm getting the following error:

```
{ error: 'fetch failed' }
{ error: 'fetch failed' }
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
```

I'm assuming this has to do with the fact that the home page is statically pre-rendered and some product details are trying to be fetched from the Medusa backend database during the build process. This works fine on my local machine (a VM on Google Cloud). My guess is that somewhere some variable is still pointing to `localhost` but I can't find that somewhere.

Here's what I've done so far:

1. Turned off the new product module by i) deleting `src/app/api` and ii) deleting the `POSTGRES_URL` environment variable from the `.env` file and iii) _not_ specifying a `POSTGRES_URL` environment variable to Vercel.
2. Set the `NEXT_PUBLIC_MEDUSA_BACKEND` environment variable in Vercel to the public IP address of the Google Cloud VM that is running my Medusa backend (`http://<public_ip>:9000/health` returns `OK`)

Any ideas what's causing this? Do I need to set the `NEXT_PUBLIC_BASE_URL` and `NEXT_PUBLIC_MEDUSA_BACKEND
` environment variables in Vercel?

**Comment by faridghar** [comment]
Possible duplicate of [this](https://github.com/medusajs/nextjs-starter-medusa/issues/210) although the error messages are different

**Comment by kasperkristensen** [comment]
Hi @faridghar, you should open your issue in the [Next starter repository](https://github.com/medusajs/nextjs-starter-medusa/tree/260bbe1c4cba15fee36739140bb1c4b90de138bc). But yes you need to add environment variables in the Vercel dashboard - see [the Vercel documentation](https://vercel.com/docs/projects/environment-variables).

I am going to close this issue as it is not related to the repo 🙂
