### ISSUE TITLE
email pass going to local host

### ISSUE THREAD

**Issue by Samarth007-2002** [medusajs/medusa-starter-default#2315]
I am hosting this app on aws ec2 and configured all .env files but as seen in the screenshot just the email pass is going to localhost

![image](https://github.com/user-attachments/assets/44b2fc50-0cae-4af8-912a-71d5bbd657ce)

**Comment by shahednasser** [comment]
Hello, can you open this issue in the [main medusa monorepo](https://github.com/medusajs/medusa) instead? Thanks!
