### ISSUE TITLE
Bug - Too many categories and static page generation fails

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/medusa-starter-default#2403]
Hello!

when we have about too many categories or 2 page categories then the Build command gives the following error when it is generating static pages for production:

#10 43.82    Generating static pages (0/4755) ...
#10 55.48    Generating static pages (1188/4755) 
#10 60.29 eH [Error]: Bad Gateway
#10 60.29     at /app/.next/server/chunks/266.js:1:77022
#10 60.29     at Generator.next (<anonymous>)
#10 60.29     at a (/app/.next/server/chunks/266.js:1:76176)
#10 60.29     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
#10 60.29   statusText: 'Bad Gateway',
#10 60.29   status: 502,
#10 60.29   digest: '1653996445'
#10 60.29 }
#10 60.29 Error: Error setting up the request: Bad Gateway
#10 60.29     at a (/app/.next/server/chunks/716.js:1:20080)
#10 60.29     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
#10 60.29     at async w (/app/.next/server/chunks/439.js:35:4036) {
#10 60.29   digest: '291655

The backend at this point shows categories api get calls are in a loop and after sometime the above error appears on storefront build.

When we delete the categories and stick to few categories then the static page generation completes without any error.

Thank you!

**Comment by christiananese** [comment]
Hey @chillpilllike, I can't reproduce this locally. Can you provide more data?

Which version of medusa are you running?
How many categories do you have?
On what machine are you running the build command?

**Comment by chillpilllike** [comment]
Fixed in recent update
