### ISSUE TITLE
What we have to insert in stripe webhook URL - Server or Worker or Storefront

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/medusa-starter-default#2534]
{medusa_url}/hooks/payment/stripe_stripe

In the above webhook for stripe what should be the URL. A backend server app URL or backend worker app URL? or storefront URL?

**Comment by sgirones** [comment]
hey @chillpilllike , you need to use the `backend_url`. Check the documentation [here](https://docs.medusajs.com/v1/plugins/payment/stripe) for more details.

**Comment by sgirones** [comment]
I linked to the old docs, my bad.

This is the pattern you need to use: `{backend_url}/hooks/payment/stripe_<id configured in the medusa config file>`

**Comment by chillpilllike** [comment]
I used the server_mode_url/hooks/payment/stripe_stripe (stripe is the id used in the medusa-config.ts file)

<img width="429" alt="Screenshot 2024-11-27 at 9 10 51 am" src="https://github.com/user-attachments/assets/d0a69cc9-0ddc-45c7-8b14-c460e21b5068">


I am getting this log in worker-mode-server and customers are unable to pay (by backend url do you mean worker-mode-url? ):


warn:    An error occurred while processing payment.webhook_received:
warn:    The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
warn:    One or more subscribers of payment.webhook_received failed. Retrying...
info:    Processing payment.webhook_received which has 1 subscribers
warn:    An error occurred while processing payment.webhook_received:
warn:    The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
warn:    One or more subscribers of payment.webhook_received failed. Retrying...
info:    Retrying payment.webhook_received which has 1 subscribers (1 of them failed)
warn:    An error occurred while processing payment.webhook_received:
warn:    The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
warn:    One or more subscribers of payment.webhook_received failed. Retrying...
info:    Processing payment.webhook_received which has 1 subscribers
warn:    An error occurred while processing payment.webhook_received:
warn:    The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
warn:    One or more subscribers of payment.webhook_received failed. Retrying...
info:    Processing payment.webhook_received which has 1 subscribers
warn:    An error occurred while processing payment.webhook_received:
warn:    The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
warn:    One or more subscribers of payment.webhook_received failed. Retrying...
info:    Retrying payment.webhook_received which has 1 subscribers (1 of them failed)
warn:    An error occurred while processing payment.webhook_received:
warn:    The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
warn:    One or more subscribers of payment.webhook_received failed. Retrying...


<img width="837" alt="Screenshot 2024-11-27 at 9 12 56 am" src="https://github.com/user-attachments/assets/696c8cb9-6480-4243-89c9-7586a4257c10">

**Comment by thetutlage** [comment]
@chillpilllike 

Can you please share the URLs you have for the worker-mode and the your Medusa API? And which URL you typed in the stripe config? Share the actual values, feel free to `redact` the domain

**Comment by chillpilllike** [comment]
Server mode: 
https://secretgreen-medusa-secretgreen-backend-server.g5edov.easypanel.host

worker mode: 
https://secretgreen-medusa-secretgreen-backend-worker.g5edov.easypanel.host


my stripe webhook is: 
https://secretgreen-medusa-secretgreen-backend-server.g5edov.easypanel.host/hooks/payment/stripe_stripe

**Comment by sradevski** [comment]
You should use the server-mode one, as that is the one that handles HTTP requests. The worker is more for handling events from the event bus, among other things.

When it comes on why it fails, it would be good if you can take some logs on what you get in the webhook, as it seems there is some data missing there. We can take it from there.

**Comment by sradevski** [comment]
No replies, closing for now
