### ISSUE TITLE
Metadata page not functional - Admin panel

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/medusa-starter-default#2535]
Hello!

when we visit the metadata page associated with a product then the page gives the following error:

An error occurred
An unexpected error occurred while rendering this page.

<img width="853" alt="Screenshot 2024-11-27 at 3 31 12 pm" src="https://github.com/user-attachments/assets/6295e483-180e-479b-b67f-f65e1b791f99">

<img width="797" alt="390361646-863d1263-72ab-4e6d-a961-c81159832502" src="https://github.com/user-attachments/assets/4b10b408-0090-4604-97ac-602d34b81574">

**Comment by kasperkristensen** [comment]
Hi @chillpilllike, thanks for the report. I have opened a PR to fix the issue: https://github.com/medusajs/medusa/pull/10312

For the future, please open your issues in the main Medusa repo https://github.com/medusajs/medusa, unless its directly related to the starter template.
