### ISSUE TITLE
Docker quickstart fails to start correctly - does not use environment variables

### ISSUE THREAD

**Issue by cfraz89** [medusajs/medusa-starter-default#31]
Hi,

Upon following [the Docker quickstart](https://docs.medusajs.com/quickstart/quick-start-docker), I observe the following errors:

```
medusa-server-default         | DriverOptionNotSetError: Driver option (database) is not set. Please set it to perform connection to the database.
medusa-server-default         | [medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
```

This appears to be due to the correct config for this environment in `medusa-config.js` - using the environment variables baked into `docker-compose.yml` and `database_type: "postgres"`, are commented out:

```js
module.exports = {
  projectConfig: {
    // redis_url: REDIS_URL,
    // For more production-like environment install PostgresQL
    // database_url: DATABASE_URL,
    // database_type: "postgres",
    database_database: "./medusa-db.sql",
    database_type: "sqlite",
    store_cors: STORE_CORS,
    admin_cors: ADMIN_CORS,
  },
  plugins,
};
```

Restoring the comments, and commenting 
```ts
    // database_database: "./medusa-db.sql",
    // database_type: "sqlite",
```

can resolve the issue.

I think maybe the quickstart should default to using environment variables, and fall back to a hardcoded sqlite config when eg. `process.env.DATABASE_URL` does not exist?

Cheers,
Chris

**Comment by olivermrbl** [comment]
Docker support has been removed from the default starter. Closing this, as we won't attend to a fix.
