### ISSUE TITLE
Error with create-medusa-app

### ISSUE THREAD

**Issue by magereact** [medusajs/medusa-starter-default#665]
Hi Guys, I'm learning MedusaJS, but when Install Medusa with create-medusa-app I get the error as shown below, can anyone help me?
<img width="983" alt="image" src="https://github.com/medusajs/medusa-starter-default/assets/68157281/f5358f9d-e260-4c28-a4e6-d145cee98925">
<img width="993" alt="image" src="https://github.com/medusajs/medusa-starter-default/assets/68157281/8301433c-beb8-436d-aec1-e3de836be63b">
<img width="910" alt="image" src="https://github.com/medusajs/medusa-starter-default/assets/68157281/da5381dd-0de6-480c-aac7-079250560aa7">
<img width="995" alt="image" src="https://github.com/medusajs/medusa-starter-default/assets/68157281/a74cebb6-4741-46e8-a5ec-b283308aa4a5">
<img width="926" alt="image" src="https://github.com/medusajs/medusa-starter-default/assets/68157281/95859d71-51be-48fb-a753-28a2cbf8a32f">

**Comment by shahednasser** [comment]
Hi @magereact , can you specify the steps you take before this error occurs? Also what OS and Node.js version are you using?

**Comment by magereact** [comment]
Hi @shahednasser,

I'm using Node version 18 on MacOS Monterey 12.7.5.
I simply used the command `npx create-medusa-app@latest --db-url my-postgressql-url`.
It runs the commands and connects to the db success, but when the admin build process gets the same error.

Thanks

**Comment by shahednasser** [comment]
Thank you for the details @magereact . Can I get you to instead open the issue in the [medusajs/medusa](https://github.com/medusajs/medusa) repository instead? Admin issues are reported there.

Will close this for now.
